export const Countries = [
  { name: "Austria", flag: "🇦🇹" },
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Brazil", flag: "🇧🇷" },
  { name: "Bulgaria", flag: "🇧🇬" },
  { name: "Egypt", flag: "🇪🇬" },
  { name: "Finland", flag: "🇫🇮" },
  { name: "France", flag: "🇫🇷" },
  { name: "Greece", flag: "🇬🇷" },
  { name: "Germany", flag: "🇩🇪" },
  { name: "Italy", flag: "🇮🇹" },
  { name: "New Zealand", flag: "🇳🇿" },
  { name: "Philippines", flag: "🇵🇭" },
  { name: "Poland", flag: "🇵🇱" },
  { name: "Romania", flag: "🇷🇴" },
  { name: "Serbia", flag: "🇷🇸" },
  { name: "South Africa", flag: "🇿🇦" },
  { name: "Spain", flag: "🇪🇸" },
  { name: "Switzerland", flag: "🇨🇭" },
  { name: "United Kingdom", flag: "🇬🇧" },
  { name: "United States of America", flag: "🇺🇸" },
];
