export const Countries = [
  { name: "Austria", code: "AUT" },
  { name: "Argentina", code: "ARG" },
  { name: "Australia", code: "AUS" },
  { name: "Brazil", code: "BRA" },
  { name: "Bulgaria", code: "BGR" },
  { name: "Egypt", code: "EGY" },
  { name: "Finland", code: "FIN" },
  { name: "France", code: "FRA" },
  { name: "Greece", code: "GRC" },
  { name: "Germany", code: "DEU" },
  { name: "Italy", code: "ITA" },
  { name: "New Zealand", code: "NZL" },
  { name: "Philippines", code: "PHL" },
  { name: "Poland", code: "POL" },
  { name: "Romania", code: "ROU" },
  { name: "Serbia", code: "SRB" },
  { name: "South Africa", code: "ZAF" },
  { name: "Spain", code: "ESP" },
  { name: "Switzerland", code: "CHE" },
  { name: "United Kingdom", code: "GBR" },
  { name: "United States of America", code: "USA" },
];
